// <auto-generated />
using System;
using BillingISPMikrotik.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingISPMikrotik.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260804204034_AddMidtransToInvoice")]
    partial class AddMidtransToInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PppPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PppUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Address = "Jl. Merdeka No 1",
                            CreatedAt = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Budi Santoso",
                            Phone = "081234567890",
                            PppPassword = "passwordbudi",
                            PppUsername = "budi",
                            ServicePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Address = "Jl. Sudirman No 2",
                            CreatedAt = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Siti Aminah",
                            Phone = "082345678901",
                            PppPassword = "passwordsiti",
                            PppUsername = "siti",
                            ServicePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Address = "Jl. Thamrin No 3",
                            CreatedAt = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Agus Pratama",
                            Phone = "083456789012",
                            PppPassword = "passwordagus",
                            PppUsername = "agus",
                            ServicePlanId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Address = "Jl. Gatot Subroto No 4",
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dewi Lestari",
                            Phone = "084567890123",
                            PppPassword = "passworddewi",
                            PppUsername = "dewi",
                            ServicePlanId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Address = "Jl. Ahmad Yani No 5",
                            CreatedAt = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Joko Widodo",
                            Phone = "085678901234",
                            PppPassword = "passwordjoko",
                            PppUsername = "joko",
                            ServicePlanId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Status = 2
                        });
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MidtransOrderId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapToken")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.MikrotikActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MikrotikActionLogs");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.PaymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.ServicePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MikrotikProfileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SpeedDown")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedUp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            MikrotikProfileName = "profile_10m",
                            Name = "Basic 10Mbps",
                            Price = 150000m,
                            SpeedDown = 10,
                            SpeedUp = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            MikrotikProfileName = "profile_20m",
                            Name = "Standard 20Mbps",
                            Price = 250000m,
                            SpeedDown = 20,
                            SpeedUp = 20
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            MikrotikProfileName = "profile_50m",
                            Name = "Premium 50Mbps",
                            Price = 400000m,
                            SpeedDown = 50,
                            SpeedUp = 50
                        });
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany()
                        .HasForeignKey("ServicePlanId");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingISPMikrotik.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany()
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.MikrotikActionLog", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.PaymentLog", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
