// <auto-generated />
using System;
using BillingISPMikrotik.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillingISPMikrotik.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723063237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PppPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PppUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("341c2af0-c515-4ab4-829b-8f469b0e66e7"),
                            Address = "Jl. Merdeka No 1",
                            CreatedAt = new DateTime(2026, 6, 23, 6, 32, 35, 640, DateTimeKind.Utc).AddTicks(3365),
                            Name = "Budi Santoso",
                            Phone = "081234567890",
                            PppPassword = "passwordbudi",
                            PppUsername = "budi",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d47cd502-8e81-4c68-a1b5-404da935add5"),
                            Address = "Jl. Sudirman No 2",
                            CreatedAt = new DateTime(2026, 5, 23, 6, 32, 35, 640, DateTimeKind.Utc).AddTicks(4072),
                            Name = "Siti Aminah",
                            Phone = "082345678901",
                            PppPassword = "passwordsiti",
                            PppUsername = "siti",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d85d406d-3056-4090-a7b4-2f0c624d2e59"),
                            Address = "Jl. Thamrin No 3",
                            CreatedAt = new DateTime(2026, 4, 23, 6, 32, 35, 640, DateTimeKind.Utc).AddTicks(4082),
                            Name = "Agus Pratama",
                            Phone = "083456789012",
                            PppPassword = "passwordagus",
                            PppUsername = "agus",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8873625f-dffd-46a3-acff-e4059777851f"),
                            Address = "Jl. Gatot Subroto No 4",
                            CreatedAt = new DateTime(2026, 3, 23, 6, 32, 35, 640, DateTimeKind.Utc).AddTicks(4087),
                            Name = "Dewi Lestari",
                            Phone = "084567890123",
                            PppPassword = "passworddewi",
                            PppUsername = "dewi",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dd202a1f-13d3-469d-afca-f7dd83a138e4"),
                            Address = "Jl. Ahmad Yani No 5",
                            CreatedAt = new DateTime(2026, 2, 23, 6, 32, 35, 640, DateTimeKind.Utc).AddTicks(4090),
                            Name = "Joko Widodo",
                            Phone = "085678901234",
                            PppPassword = "passwordjoko",
                            PppUsername = "joko",
                            Status = 2
                        });
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServicePlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.MikrotikActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("MikrotikActionLogs");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.PaymentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.ServicePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MikrotikProfileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("SpeedDown")
                        .HasColumnType("integer");

                    b.Property<int>("SpeedUp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ceb16e3d-b847-445b-baaf-88712278c68e"),
                            MikrotikProfileName = "profile_10m",
                            Name = "Basic 10Mbps",
                            Price = 150000m,
                            SpeedDown = 10,
                            SpeedUp = 10
                        },
                        new
                        {
                            Id = new Guid("1b9da367-44e8-4ee3-9521-4de0c768ad43"),
                            MikrotikProfileName = "profile_20m",
                            Name = "Standard 20Mbps",
                            Price = 250000m,
                            SpeedDown = 20,
                            SpeedUp = 20
                        },
                        new
                        {
                            Id = new Guid("dc527fe1-1447-4d10-8634-b5f4b3f69186"),
                            MikrotikProfileName = "profile_50m",
                            Name = "Premium 50Mbps",
                            Price = 400000m,
                            SpeedDown = 50,
                            SpeedUp = 50
                        });
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillingISPMikrotik.Domain.Entities.ServicePlan", "ServicePlan")
                        .WithMany()
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.MikrotikActionLog", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BillingISPMikrotik.Domain.Entities.PaymentLog", b =>
                {
                    b.HasOne("BillingISPMikrotik.Domain.Entities.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
